reviews
AlexPlu/project-group-8 pull request #1
Opened 2023-12-20 22:47 UTC by Halyna-Mukha

2023-12-21 00:20 UTC, AlexPlu requested changes

2023-12-21 00:20 UTC, AlexPlu commented on src/css/reviews.css
> +  .reviews-text {
не соответсвует макету, не хватает `opacity`

2023-12-21 00:20 UTC, AlexPlu commented on src/css/reviews.css
> +    margin-bottom: 24px;
форматировие? и добавь пустую линию между селекторами

2023-12-21 00:20 UTC, AlexPlu commented on src/css/reviews.css
> +  font-family: Inter;
font-family не нужно писать, он уже в руте прописан

2023-12-21 00:20 UTC, AlexPlu commented on src/css/reviews.css
> +.container {
нужно забрать правки из main, такой класс уже есть в main, если не получиться, пиши помогу

2023-12-21 00:20 UTC, AlexPlu commented on src/partials/reviews.html
> +      <div class="reviews-list-mobile">
зачем тут div? если только для того чтобы скрыть на таблет и mobile, то ты можем просто применть на сам ли  `display: none`

2023-12-21 00:20 UTC, AlexPlu commented on src/css/reviews.css
> +  width: 335px;
два раза width указала, и на 320px тоже должно нормально отображатся

2023-12-21 00:20 UTC, AlexPlu commented on src/css/reviews.css
> +    margin-bottom: 24px;
и давай чтобы не вешать атрибут class на каждую картинку, используем селектор потомков, типа `.reviews-list img`

2023-12-21 00:20 UTC, AlexPlu commented on src/css/reviews.css
> +    .reviews-menu {
отсутствует центрирование

`justify-content` ?

2023-12-21 00:20 UTC, AlexPlu commented on src/partials/reviews.html
> +              src="./YachtJet_files/victoria-romashenko-tablet.png"
что это за `YachtJet_files` ?

2023-12-21 00:20 UTC, AlexPlu commented on src/img/reviews/victoria-romashenko-tablet@2x.png
картинки все размытые, нужно с макета качать соурс файл, и его оптимизировать под все устройства,

2023-12-21 07:57 UTC, Halyna-Mukha commented on src/partials/reviews.html
> +              src="./YachtJet_files/victoria-romashenko-tablet.png"
хороший вопрос)

2023-12-21 08:10 UTC, Halyna-Mukha commented on src/css/reviews.css
> +  font-family: Inter;
убрала, а также фонт сайз 16 и фонт вейт почистила 400

2023-12-21 08:12 UTC, Halyna-Mukha commented on src/partials/reviews.html
> +      <div class="reviews-list-mobile">
если я задам на ли дисплей нон, у меня же и первый ли спрячется. на мобайл 1 ли, на таблет 2 ли, и на десктопе 3 ли. как это сделать иначе?

2023-12-21 08:17 UTC, Halyna-Mukha commented on src/css/reviews.css
> +  width: 335px;
тут по макету на мобайл ширина 335, на таблет 336 и соответственно содержимое 303 и 304 по ширине. это нужно исправить на 320? или я что-то не так поняла?

2023-12-21 08:30 UTC, Halyna-Mukha commented on src/img/reviews/victoria-romashenko-tablet@2x.png
что за соурс файл?

2023-12-21 08:48 UTC, Halyna-Mukha commented on src/css/reviews.css
> +.container {
не поняла

2023-12-23 00:35 UTC, AlexPlu commented on src/css/reviews.css
> +  width: 335px;
тут должно было быть max-width, тогда на 320px тоже будет всё ок, ну то не критично

2023-12-23 00:36 UTC, AlexPlu approved these changes

2023-12-23 00:37 UTC, merged